annonces_home:
    path: /
    defaults:
        _controller: AnnoncesBundle:Annonces:home
        
annonces_add:
    path: /add
    defaults:
        _controller: AnnoncesBundle:Annonces:add

annonces_add_category:
    path: /addCategory
    defaults:
        _controller: AnnoncesBundle:Annonces:addCategory

annonces_view:
    path: /view/{id}
    defaults:
        _controller: AnnoncesBundle:Annonces:view

annonces_edit:
    path: /edit/{id}
    defaults:
        _controller: AnnoncesBundle:Annonces:edit
        
annonces_delete:
    path: /delete/{id}
    defaults:
        _controller: AnnoncesBundle:Annonces:delete
               
villes:
    resource: "@AnnoncesBundle/Controller/ApiVillesController.php"
    type: annotation
    defaults: {_format: json}
    prefix: /api
    
categories:
    resource: "@AnnoncesBundle/Controller/ApiCategoriesController.php"
    type: annotation
    defaults: {_format: json}
    prefix: /api
    
annonces:
    resource: "@AnnoncesBundle/Controller/ApiAnnoncesController.php"
    type: annotation
    defaults: {_format: json}
    prefix: /api
    