users_signup:
     path: /signup
     defaults:
         _controller: UsersBundle:Main:signUp

users_signin:
    path: /login
    defaults:
        _controller: UsersBundle:Main:signIn

users_signout:
    path: /logout

users_profile:
    path: /account/profile
    defaults:
        _controller: UsersBundle:Main:viewProfile

users_adverts:
    path: /account/adverts
    defaults:
        _controller: UsersBundle:Main:viewAdverts
