<?php

namespace AnnoncesBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAnnonces(array $criterias, $withPhotos=false)
	{
		$query = $this->createQueryBuilder('a')
						->innerJoin('a.category', 'c')
						->addSelect('c')
						->innerJoin('a.city', 'v')
						->addSelect('v');
		
		if($withPhotos)
		{
			$query
				->leftJoin('a.photos', 'p')
				->addSelect('p');
		}

		if(isset($criterias['category']) && !empty($criterias['category']) && isset($criterias['city']) && !empty($criterias['city']))
		{
			$query
				->where('c.name = :category')
				->setParameter('category', $criterias['category'])
				->andWhere('v.name = :city')
				->setParameter('city', $criterias['city']);
			
		}
		elseif(isset($criterias['category']) && !empty($criterias['category']))
		{
			$query
				->where('c.name = :category')
				->setParameter('category', $criterias['category']);
		}
		else
		{
			$query
				->andWhere('v.name = :city')
				->setParameter('city', $criterias['city']);
		}
		
		$query
			->andWhere('a.expireAt >= :now')
			->setParameter('now', new \Datetime('now'));
		
		return $query->getQuery()->getResult();
	}
	
	public function findAnnonceWithCatAndPhotos($id)
	{
		$query = $this->createQueryBuilder('a');
		
		$query
		->innerJoin('a.category', 'c')
		->addSelect('c')
		->leftJoin('a.photos', 'p')
		->addSelect('p')
        ->innerJoin('a.city', 'ci')
        ->addSelect('ci')
        ->innerJoin('a.owner', 'o')
        ->addSelect('o')
		->where('a.id = :id')
		->andWhere('a.expireAt >= :now')
		->setParameter('now', new \Datetime('now'))
		->setParameter('id', $id);
		
		return $query->getQuery()->getOneOrNullResult();
	}
	
}
