<?php

namespace AnnoncesBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUnassociatedPhotos()
	{
		$query = $this
					->createQueryBuilder('p')
					->where('p.annonce IS NULL')
					->andWhere('p.expiredAt <= :dateExpiration')
					->setParameter('dateExpiration', new \Datetime('now'));
		
		return $query->getQuery()->getResult();
	}
}
