<?php

namespace AnnoncesBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAnnonces($category, $city)
	{
		$query = $this->createQueryBuilder('a');
		
		$query
			->innerJoin('a.category', 'c')
			->addSelect('c')
			->where('c.name = :category')
			->setParameter('category', $category)
			->andWhere('a.city = :city')
			->setParameter('city', $city)
			->andWhere('a.expireAt >= :now')
			->setParameter('now', new \Datetime('now'));
		
		return $query->getQuery()->getArrayResult();
	}
	
	public function findAnnoncesWithPhotos($category, $city)
	{
		$query = $this->createQueryBuilder('a');
	
		$query
		->innerJoin('a.category', 'c')
		->addSelect('c')
		->leftJoin('a.photos', 'p')
		->addSelect('p')
		->where('c.name = :category')
		->setParameter('category', $category)
		->andWhere('a.city = :city')
		->setParameter('city', $city)
		->andWhere('a.expireAt >= :now')
		->setParameter('now', new \Datetime('now'));
	
		return $query->getQuery()->getArrayResult();
	}
	
	public function findAnnoncesByCity($city)
	{
		$query = $this->createQueryBuilder('a');
	
		$query
		->innerJoin('a.category', 'c')
		->addSelect('c')
		->andWhere('a.city = :city')
		->andWhere('a.expireAt >= :now')
		->setParameter('now', new \Datetime('now'))
		->setParameter('city', $city);
	
		return $query->getQuery()->getArrayResult();
	}
	
	public function findAnnoncesByCityWithPhotos($city)
	{
		$query = $this->createQueryBuilder('a');
	
		$query
		->innerJoin('a.category', 'c')
		->addSelect('c')
		->leftJoin('a.photos', 'p')
		->addSelect('p')
		->andWhere('a.city = :city')
		->andWhere('a.expireAt >= :now')
		->setParameter('now', new \Datetime('now'))
		->setParameter('city', $city);
	
		return $query->getQuery()->getArrayResult();
	}
	
	public function findAnnoncesByCategory($category)
	{
		$query = $this->createQueryBuilder('a');
	
		$query
		->innerJoin('a.category', 'c')
		->addSelect('c')
		->where('c.name = :category')
		->andWhere('a.expireAt >= :now')
		->setParameter('now', new \Datetime('now'))
		->setParameter('category', $category);
	
		return $query->getQuery()->getArrayResult();
	}
	
	public function findAnnoncesByCategoryWithPhotos($category)
	{
		$query = $this->createQueryBuilder('a');
	
		$query
		->innerJoin('a.category', 'c')
		->addSelect('c')
		->leftJoin('a.photos', 'p')
		->addSelect('p')
		->where('c.name = :category')
		->andWhere('a.expireAt >= :now')
		->setParameter('now', new \Datetime('now'))
		->setParameter('category', $category);
	
		return $query->getQuery()->getArrayResult();
	}
	
	public function findAnnonceWithCatAndPhotos($id)
	{
		$query = $this->createQueryBuilder('a');
		
		$query
		->innerJoin('a.category', 'c')
		->addSelect('c')
		->leftJoin('a.photos', 'p')
		->addSelect('p')
		->where('a.id = :id')
		->andWhere('a.expireAt >= :now')
		->setParameter('now', new \Datetime('now'))
		->setParameter('id', $id);
		
		return $query->getQuery()->getOneOrNullResult();
	}
	
}
